/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.menu;

/**
 *
 * @author Dhenis
 */
import main.mainFrame;
import javax.swing.*;
import java.awt.event.*;

public class menuPanel extends javax.swing.JPanel {

    /**
     * Creates new form gamePanel
     */
    private mainFrame mainFrame;
    public menuPanel(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnOption = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 65)); // NOI18N
        jLabel3.setText("KYOJIN GEMU");

        btnNew.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnNew.setText("NEW GAME");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnOption.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnOption.setText("OPTION");
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnNew)
                    .addComponent(btnOption)
                    .addComponent(btnExit))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addComponent(btnNew)
                .addGap(18, 18, 18)
                .addComponent(btnOption)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new storyPanel(mainFrame));
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOption;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
