/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.menu;

/**
 *
 * @author Dhenis
 */
import ui.menu.menuPanel;
import main.mainFrame;
import javax.swing.*;
import java.awt.event.*;
import ui.auth.*;

public class startPanel extends javax.swing.JPanel {

    /**
     * Creates new form menuPanel
     */
    private mainFrame mainFrame;
    public startPanel() {
        initComponents();
    }

    public startPanel(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setFont(new java.awt.Font("Mistral", 1, 54)); // NOI18N
        btnStart.setBorder(javax.swing.BorderFactory.createMatteBorder(
            0, 1, 0, 1,
            new java.awt.Color(230,230,230)
        )
    );
    btnStart.setBorderPainted(false);
    btnStart.setContentAreaFilled(false);
    btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnStartMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnStartMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnStartMouseExited(evt);
        }
    });
    btnStart.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnStartActionPerformed(evt);
        }
    });
    add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 349, 100, 15));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/background/START.png"))); // NOI18N
    add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 810, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
        mainFrame.showPanel(new loginPage(mainFrame));
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
       btnStart.setBorderPainted(true);
       mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\HOVER SFX.wav");
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
        btnStart.setBorderPainted(false);
    }//GEN-LAST:event_btnStartMouseExited

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
