/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.story;

/**
 *
 * @author Dhenis
 */

import main.mainFrame;

public class Scene2 extends javax.swing.JPanel {

    private mainFrame mainFrame;
    
    public Scene2(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klik = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        klik.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        klik.setText("Klik di mana saja untuk lanjut");
        add(klik, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 180, 20));

        next.setToolTipText("");
        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/dialog/SCENE 2 DIALOG.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new Scene3(mainFrame));
    }//GEN-LAST:event_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel klik;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
